Feature/implement game stat
hienlq16103/Smash-Zombies pull request #6
Opened 2024-09-26 16:10 UTC by RaidenEiMyFriend

game stats added

2024-09-27 08:52 UTC, hienlq16103 requested changes

2024-09-27 08:52 UTC, hienlq16103 commented on Scripts/game_stats.py
> +class GameStat:
Thiếu cách dòng

2024-09-27 08:52 UTC, hienlq16103 commented on Scripts/game_stats.py
> +class GameStat:
Thiếu docstring mô tả class
Tham khảo thêm: http://daouzli.com/blog/docstring.html#restructuredtext

2024-09-27 08:52 UTC, hienlq16103 commented on Scripts/game_stats.py
> +        self.font = pygame.font.Font(None, 36)
Thiếu docstring mô tả hàm

2024-09-27 08:52 UTC, hienlq16103 commented on Scripts/game_stats.py
> +        return self.hit_count / self.miss_count
Thiếu docstring mô tả property

2024-09-27 08:52 UTC, hienlq16103 commented on Scripts/game_stats.py
> +            self.miss_count += 1
Thiếu docstring mô tả hàm

2024-09-27 08:52 UTC, hienlq16103 commented on Scripts/game_stats.py
> +        screen.blit(score_text, (10, 130))
Thiếu docstring

2024-09-27 08:52 UTC, hienlq16103 commented on Scripts/game_stats.py
> +
Dư 1 dòng cuối file

2024-09-27 08:52 UTC, hienlq16103 commented on Scripts/game_stats.py
> +        self.font = pygame.font.Font(None, 36)
Mấy biến này không truy cập từ bên ngoài thì mình để private

2024-09-27 08:54 UTC, hienlq16103 requested changes

2024-09-27 08:54 UTC, hienlq16103 commented on main.py
> +        self.__background = pygame.transform.scale(self.__background, (self.width, self.height))
Cái này không nằm trong task của ông, trả về như cũ. sau đó merge từ main mới nhất qua

2024-09-27 08:54 UTC, hienlq16103 commented on main.py
> +        self.__displaying_surface.blit(self.__background, (0, 0))
Cái này không nằm trong task của ông, trả về như cũ. sau đó merge từ main mới nhất qua

2024-09-28 13:26 UTC, RaidenEiMyFriend commented on Scripts/game_stats.py
> +class GameStat:
![rs1](https://github.com/user-attachments/assets/9db5c867-6da2-4b34-a067-d5e4a5c322b1)

2024-09-28 13:27 UTC, RaidenEiMyFriend commented on Scripts/game_stats.py
> +class GameStat:
![image](https://github.com/user-attachments/assets/0418db36-f710-4cbe-83e9-c01a062601d7)

2024-09-28 13:27 UTC, RaidenEiMyFriend commented on Scripts/game_stats.py
> +        self.font = pygame.font.Font(None, 36)
![image](https://github.com/user-attachments/assets/08fc9e52-a963-4f29-9fa6-1f9585e3d354)

2024-09-28 13:28 UTC, RaidenEiMyFriend commented on Scripts/game_stats.py
> +        return self.hit_count / self.miss_count
![image](https://github.com/user-attachments/assets/41252971-3adf-4d13-97d0-cb294a6a2499)

2024-09-28 13:28 UTC, RaidenEiMyFriend commented on Scripts/game_stats.py
> +            self.miss_count += 1
![image](https://github.com/user-attachments/assets/4b00bf9a-a47f-447e-b2c0-6b247d8a9d14)

2024-09-28 13:29 UTC, RaidenEiMyFriend commented on Scripts/game_stats.py
> +        screen.blit(score_text, (10, 130))
![image](https://github.com/user-attachments/assets/8c6df013-3523-4ed8-99a8-03ec039ed36f)

2024-09-28 13:29 UTC, RaidenEiMyFriend commented on Scripts/game_stats.py
> +
![image](https://github.com/user-attachments/assets/8d775079-e3bd-41f0-8fc1-12ff4077218d)

2024-09-28 13:30 UTC, RaidenEiMyFriend commented on Scripts/game_stats.py
> +        self.font = pygame.font.Font(None, 36)
![Uploading image.png…]()

2024-09-28 13:31 UTC, RaidenEiMyFriend commented on Scripts/game_stats.py
> +        self.font = pygame.font.Font(None, 36)
![image](https://github.com/user-attachments/assets/1c843d22-6fd0-49d0-97ca-b6b946b43540)

2024-09-29 10:29 UTC, nttdung0605 approved these changes

2024-09-29 11:23 UTC, hienlq16103 approved these changes

2024-09-29 11:55 UTC, merged